<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SCA-WS401" ignored="13" name="Appium" tests="3" failures="2" timestamp="07 Dec 2017 21:37:54 GMT" time="122.548" errors="0">
  <testcase name="ValidCallTest" time="26.851" classname="Tests.HiyaTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Tests.HiyaTests.ValidCallTest(HiyaTests.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidCallTest -->
  <testcase name="ValidCallTest" time="26.025" classname="Tests.HiyaTests"/>
  <testcase name="ValidCallTest" time="26.326" classname="Tests.HiyaTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Tests.HiyaTests.ValidCallTest(HiyaTests.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidCallTest -->
  <testcase name="SignInText" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- SignInText -->
  <testcase name="PermissionMessage" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- PermissionMessage -->
  <testcase name="MarketingMessage" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- MarketingMessage -->
  <testcase name="CallBlockingView" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- CallBlockingView -->
  <testcase name="RedirectToSignInPage" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- RedirectToSignInPage -->
  <testcase name="AllowContacAccess" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- AllowContacAccess -->
  <testcase name="AllowMakeCalls" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- AllowMakeCalls -->
  <testcase name="SpamCallTest" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- SpamCallTest -->
  <testcase name="EnableDrawOverMessageAndAccept" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- EnableDrawOverMessageAndAccept -->
  <testcase name="FraudCallTest" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- FraudCallTest -->
  <testcase name="MenuIsDisplayed" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- MenuIsDisplayed -->
  <testcase name="EnableDrawOverMessage" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- EnableDrawOverMessage -->
  <testcase name="UserNotSigned" time="0.0" classname="Tests.HiyaTests">
    <ignored/>
  </testcase> <!-- UserNotSigned -->
</testsuite> <!-- Appium -->
